"""initial BaatX schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-21

Creates every table for users, tenancy, CRM, conversations, follow-ups,
reports, billing, WhatsApp and audit logging. All tenant-scoped tables carry
business_id with an index, and customers are unique on
(business_id, normalized_phone) so the same phone can exist in other
businesses while staying fully isolated.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import app.db.base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vertical', sa.String(length=32), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('actor_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', app.db.base.GUID(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_business_action', 'audit_logs', ['business_id', 'action'], unique=False)
    op.create_index('ix_audit_business_created', 'audit_logs', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_table('business_memberships',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'user_id', name='uq_membership_business_user')
    )
    op.create_index(op.f('ix_business_memberships_business_id'), 'business_memberships', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_memberships_user_id'), 'business_memberships', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('normalized_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('product', sa.String(length=160), nullable=True),
    sa.Column('service', sa.String(length=160), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timeline', sa.String(length=160), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('price_discussion', sa.Text(), nullable=True),
    sa.Column('purchase_intent', sa.String(length=16), nullable=False),
    sa.Column('lead_status', sa.String(length=24), nullable=False),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('pain_points', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('objections', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('competitors', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('decision_maker', sa.String(length=160), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('field_confidence', app.db.base.JSONBCompat(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'normalized_phone', name='uq_customer_business_phone')
    )
    op.create_index('ix_customers_business_followup', 'customers', ['business_id', 'next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index('ix_customers_business_name', 'customers', ['business_id', 'name'], unique=False)
    op.create_index('ix_customers_business_updated', 'customers', ['business_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_customers_lead_status'), 'customers', ['lead_status'], unique=False)
    op.create_index(op.f('ix_customers_normalized_phone'), 'customers', ['normalized_phone'], unique=False)
    op.create_index(op.f('ix_customers_owner_user_id'), 'customers', ['owner_user_id'], unique=False)
    op.create_table('query_categories',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'stat_date', 'category', name='uq_query_cat_day')
    )
    op.create_index('ix_query_cat_business_date', 'query_categories', ['business_id', 'stat_date'], unique=False)
    op.create_index(op.f('ix_query_categories_business_id'), 'query_categories', ['business_id'], unique=False)
    op.create_table('report_metrics',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'metric_date', 'metric_key', name='uq_metric_day_key')
    )
    op.create_index('ix_metrics_business_date', 'report_metrics', ['business_id', 'metric_date'], unique=False)
    op.create_index(op.f('ix_report_metrics_business_id'), 'report_metrics', ['business_id'], unique=False)
    op.create_table('report_snapshots',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('metrics', app.db.base.JSONBCompat(), nullable=False),
    sa.Column('ai_insights', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('generated_by_model', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period', 'period_start', 'user_id', name='uq_report_period')
    )
    op.create_index(op.f('ix_report_snapshots_business_id'), 'report_snapshots', ['business_id'], unique=False)
    op.create_index('ix_reports_business_period', 'report_snapshots', ['business_id', 'period', 'period_start'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('plan', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('monthly_minutes_quota', sa.Integer(), nullable=False),
    sa.Column('monthly_ai_requests_quota', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', name='uq_subscription_business')
    )
    op.create_index(op.f('ix_subscriptions_business_id'), 'subscriptions', ['business_id'], unique=False)
    op.create_table('usage',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'usage_date', 'metric', name='uq_usage_day_metric')
    )
    op.create_index('ix_usage_business_date', 'usage', ['business_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_usage_business_id'), 'usage', ['business_id'], unique=False)
    op.create_table('ai_processing_jobs',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('created_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stage_label', sa.String(length=80), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('audio_blob_name', sa.String(length=512), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_mime_type', sa.String(length=80), nullable=True),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language_detected', sa.String(length=16), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hinted_customer_id', app.db.base.GUID(), nullable=True),
    sa.Column('hinted_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hinted_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_job_business_idem')
    )
    op.create_index(op.f('ix_ai_processing_jobs_business_id'), 'ai_processing_jobs', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_jobs_created_by_user_id'), 'ai_processing_jobs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_jobs_status'), 'ai_processing_jobs', ['status'], unique=False)
    op.create_index('ix_jobs_business_status', 'ai_processing_jobs', ['business_id', 'status'], unique=False)
    op.create_table('leads',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('assigned_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'customer_id', name='uq_lead_business_customer')
    )
    op.create_index(op.f('ix_leads_assigned_user_id'), 'leads', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index('ix_leads_business_status', 'leads', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_business_id'), 'tasks', ['business_id'], unique=False)
    op.create_index('ix_tasks_business_status_due', 'tasks', ['business_id', 'status', 'due_at'], unique=False)
    op.create_index(op.f('ix_tasks_customer_id'), 'tasks', ['customer_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('to_phone', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('drafted_by_ai', sa.Boolean(), nullable=False),
    sa.Column('approved_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_business_status', 'whatsapp_messages', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_business_id'), 'whatsapp_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_customer_id'), 'whatsapp_messages', ['customer_id'], unique=False)
    op.create_table('ai_extractions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('job_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=True),
    sa.Column('payload', app.db.base.JSONBCompat(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('needs_confirmation', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('stt_provider', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_business_id'), 'ai_extractions', ['business_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_customer_id'), 'ai_extractions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_extractions_job_id'), 'ai_extractions', ['job_id'], unique=False)
    op.create_index('ix_extractions_business_created', 'ai_extractions', ['business_id', 'created_at'], unique=False)
    op.create_table('conversation_events',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('job_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('highlights', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_categories', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('primary_query_category', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_processing_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_events_business_id'), 'conversation_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversation_events_customer_id'), 'conversation_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversation_events_primary_query_category'), 'conversation_events', ['primary_query_category'], unique=False)
    op.create_index('ix_events_business_customer_created', 'conversation_events', ['business_id', 'customer_id', 'created_at'], unique=False)
    op.create_table('conversion_events',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('lead_id', app.db.base.GUID(), nullable=True),
    sa.Column('value_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('converted_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['converted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversion_business_created', 'conversion_events', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversion_events_business_id'), 'conversion_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_customer_id'), 'conversion_events', ['customer_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('customer_id', app.db.base.GUID(), nullable=False),
    sa.Column('job_id', app.db.base.GUID(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_time_known', sa.Boolean(), nullable=False),
    sa.Column('assigned_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescheduled_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_requested_callback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_processing_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_business_id'), 'follow_ups', ['business_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_customer_id'), 'follow_ups', ['customer_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_due_at'), 'follow_ups', ['due_at'], unique=False)
    op.create_index(op.f('ix_follow_ups_status'), 'follow_ups', ['status'], unique=False)
    op.create_index('ix_followups_assignee_due', 'follow_ups', ['assigned_user_id', 'due_at'], unique=False)
    op.create_index('ix_followups_business_customer', 'follow_ups', ['business_id', 'customer_id'], unique=False)
    op.create_index('ix_followups_business_due_status', 'follow_ups', ['business_id', 'due_at', 'status'], unique=False)
    op.create_table('lead_status_transitions',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('lead_id', app.db.base.GUID(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('changed_by_user_id', app.db.base.GUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_status_transitions_business_id'), 'lead_status_transitions', ['business_id'], unique=False)
    op.create_index(op.f('ix_lead_status_transitions_lead_id'), 'lead_status_transitions', ['lead_id'], unique=False)
    op.create_index('ix_lst_business_created', 'lead_status_transitions', ['business_id', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('business_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('customer_id', app.db.base.GUID(), nullable=True),
    sa.Column('follow_up_id', app.db.base.GUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('data', app.db.base.JSONBCompat(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index('ix_notifications_dedupe', 'notifications', ['business_id', 'dedupe_key'], unique=True)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_dedupe', table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_lst_business_created', table_name='lead_status_transitions')
    op.drop_index(op.f('ix_lead_status_transitions_lead_id'), table_name='lead_status_transitions')
    op.drop_index(op.f('ix_lead_status_transitions_business_id'), table_name='lead_status_transitions')
    op.drop_table('lead_status_transitions')
    op.drop_index('ix_followups_business_due_status', table_name='follow_ups')
    op.drop_index('ix_followups_business_customer', table_name='follow_ups')
    op.drop_index('ix_followups_assignee_due', table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_status'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_due_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_customer_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_business_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_conversion_events_customer_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_business_id'), table_name='conversion_events')
    op.drop_index('ix_conversion_business_created', table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index('ix_events_business_customer_created', table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_primary_query_category'), table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_customer_id'), table_name='conversation_events')
    op.drop_index(op.f('ix_conversation_events_business_id'), table_name='conversation_events')
    op.drop_table('conversation_events')
    op.drop_index('ix_extractions_business_created', table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_job_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_customer_id'), table_name='ai_extractions')
    op.drop_index(op.f('ix_ai_extractions_business_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    op.drop_index(op.f('ix_whatsapp_messages_customer_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_business_id'), table_name='whatsapp_messages')
    op.drop_index('ix_wa_business_status', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_tasks_customer_id'), table_name='tasks')
    op.drop_index('ix_tasks_business_status_due', table_name='tasks')
    op.drop_index(op.f('ix_tasks_business_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index('ix_leads_business_status', table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_user_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_jobs_business_status', table_name='ai_processing_jobs')
    op.drop_index(op.f('ix_ai_processing_jobs_status'), table_name='ai_processing_jobs')
    op.drop_index(op.f('ix_ai_processing_jobs_created_by_user_id'), table_name='ai_processing_jobs')
    op.drop_index(op.f('ix_ai_processing_jobs_business_id'), table_name='ai_processing_jobs')
    op.drop_table('ai_processing_jobs')
    op.drop_index(op.f('ix_usage_business_id'), table_name='usage')
    op.drop_index('ix_usage_business_date', table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_subscriptions_business_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_reports_business_period', table_name='report_snapshots')
    op.drop_index(op.f('ix_report_snapshots_business_id'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_index(op.f('ix_report_metrics_business_id'), table_name='report_metrics')
    op.drop_index('ix_metrics_business_date', table_name='report_metrics')
    op.drop_table('report_metrics')
    op.drop_index(op.f('ix_query_categories_business_id'), table_name='query_categories')
    op.drop_index('ix_query_cat_business_date', table_name='query_categories')
    op.drop_table('query_categories')
    op.drop_index(op.f('ix_customers_owner_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_normalized_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_lead_status'), table_name='customers')
    op.drop_index('ix_customers_business_updated', table_name='customers')
    op.drop_index('ix_customers_business_name', table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_index('ix_customers_business_followup', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_business_memberships_user_id'), table_name='business_memberships')
    op.drop_index(op.f('ix_business_memberships_business_id'), table_name='business_memberships')
    op.drop_table('business_memberships')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_business_created', table_name='audit_logs')
    op.drop_index('ix_audit_business_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('businesses')
    # ### end Alembic commands ###
